apis:
  openalex:
    base_url: https://api.openalex.org/works
  unpaywall:
    base_url: https://api.unpaywall.org/v2
    email: domagojhack@gmail.com
  zenodo:
    base_url: https://zenodo.org/api/records
  dryad:
    base_url: https://datadryad.org/api/v2/datasets
  elsevier:
    base_url: https://api.elsevier.com/content/article
    api_key: 271335174a3c7e20e2878346dbcfb12e