# Keywords for EcoOpen package to identify data and code availability statements

keywords = {
    "data_availability": [
        "Data Availability",
        "Availability of Data",
        "Data Access",
        "Supporting Information",
        "Supplementary Information",
    ],
    "data": [
        "data",
        "dataset",
        "datasets",
        "raw data",
        "processed data",
        "supporting data",
        "supplementary data",
    ],
    "all_data": [
        "all data",
        "complete data",
        "full data",
        "entire dataset",
    ],
    "dataset_name": [
        "database",
        "repository",
        "archive",
    ],
    "available": [
        "available",
        "accessible",
        "provided",
        "shared",
        "deposited",
        "publicly available",
        "freely available",
    ],
    "was_available": [
        "was available",
        "were available",
        "made available",
        "has been made available",
        "have been made available",
    ],
    "not_available": [
        "not available",
        "unavailable",
        "not shared",
        "not provided",
        "not accessible",
        "not deposited",
    ],
    "not_data": [
        "no data",
        "no dataset",
        "no datasets",
        "no raw data",
        "no processed data",
    ],
    "repositories": [
        "Dryad",
        "Zenodo",
        "Figshare",
        "Dataverse",
        "Mendeley Data",
        "OSF",
        "Open Science Framework",
    ],
    "field_specific_repo": [
        "GenBank",
        "SRA",
        "Sequence Read Archive",
        "GEO",
        "Gene Expression Omnibus",
        "ArrayExpress",
        "ENA",
        "European Nucleotide Archive",
    ],
    "github": [
        "GitHub",
        "gitlab",
        "bitbucket",
    ],
    "upon_request": [
        "upon request",
        "on request",
        "by request",
        "available upon reasonable request",
        "available on reasonable request",
    ],
    "supplement": [
        "supplementary material",
        "supplemental material",
        "supporting material",
        "supplementary information",
        "supplemental information",
        "supporting information",
        "supplementary data",
        "supplemental data",
        "supporting data",
        "supplementary files",
        "supplemental files",
        "supporting files",
    ],
    "supplemental_table_name": [
        "Table S[0-9]+",
        "Figure S[0-9]+",
        "Appendix S[0-9]+",
        "Suppl Table [0-9]+",
        "Suppl Fig [0-9]+",
        "Supplementary Table [0-9]+",
        "Supplementary Figure [0-9]+",
    ],
    "supplemental_dataset": [
        "Dataset S[0-9]+",
        "Suppl Dataset [0-9]+",
        "Supplementary Dataset [0-9]+",
    ],
    "source_code": [
        "source code",
        "software",
        "code",
        "scripts",
        "program",
        "algorithm",
    ],
    "accession_nr": [
        r"[A-Z][0-9]{6,8}",           # GenBank/EMBL/DDBJ (e.g., AF123456)
        r"SRR[0-9]{6,}",              # SRA (Sequence Read Archive, e.g., SRR123456)
        r"PRJ(NA|EB|DB)[0-9]{6,}",    # BioProject (e.g., PRJNA123456)
        r"[A-Z]{2}[0-9]{6}",          # Another format (e.g., AB123456)
        r"[A-Z]{1,2}_[0-9]{5,8}",     # Format with underscore (e.g., NC_123456)
        r"[A-Z]{3}[0-9]{5,}",         # Another format (e.g., GEO12345)
    ],
    "code_availability": [
        "Code Availability",
        "Software Availability",
        "Availability of Code",
        "Supporting Information",
    ],
}

DATA_AVAILABILITY_KEYWORDS = [
    "data availability",
    "availability of data",
    "data accessibility",
    "data access",
    "data sharing",
    "data and code availability",
    "data and materials availability",
    "data statement",
    "data are available",
    "data can be found",
    "data are stored",
    "data are deposited",
    "data are provided",
    "data are accessible",
    "data are archived",
    "supporting information",
    "supplementary information",
    "supplementary materials",
    "supplemental material",
    "supplemental data",
    "appendix",
    "si appendix",
    "online resource",
    "supplementary table",
    "supplementary file",
    "supplementary dataset",
    "supplementary data",
    "supporting data",
    "supporting files",
    "supporting materials",
    "data repository",
    "data deposited in",
    "data hosted at",
    "data available at",
    "data available from",
    "data available upon request",
    "data available on request",
    "data available in",
    "data available through",
    "data available via",
    "data available online",
    "data available as",
    "data available under",
    "data available within",
    "data available with",
    "data available for download",
    "data can be accessed at",
    "data can be requested from",
    "data can be obtained from",
    "data can be downloaded from",
    "data can be retrieved from",
    "data can be supplied upon request",
    "data can be made available",
    "data will be made available",
    "data will be provided",
    "data will be deposited",
    "data will be shared",
    "data will be accessible",
    "data will be archived",
    "data will be available",
    "data will be supplied",
    "data will be released",
    "data will be published",
    "data will be submitted",
    "data will be uploaded",
    "data will be included",
    "data will be stored",
    "data will be hosted",
    "data will be found",
    "data will be obtained",
    "data will be retrieved",
    "data will be requested",
    "data will be given",
    "data will be sent",
    "data will be delivered",
    "data will be distributed",
    "data will be transferred",
    "data will be transmitted",
    "data will be communicated",
    "data will be disclosed",
    "data will be referenced",
    "data will be cited",
    "data will be listed",
    "data will be documented",
    "data will be reported",
    "data will be noted",
    "data will be mentioned",
    "data will be identified",
    "data will be named",
    "data will be labeled",
    "data will be tagged",
    "data will be marked",
    "data will be highlighted",
    "data will be emphasized",
    "data will be described",
    "data will be explained",
    "data will be clarified",
    "data will be interpreted",
    "data will be detailed",
    "data will be specified",
    "data will be itemized",
    "data will be enumerated",
    "data will be catalogued",
    "data will be registered",
    "data will be recorded",
]

CODE_AVAILABILITY_KEYWORDS = [
    "code availability",
    "software availability",
    "availability of code",
    "availability of software",
    "source code availability",
    "code and data availability",
    "code and materials availability",
    "code statement",
    "software statement",
    "code is available",
    "software is available",
    "code can be found",
    "software can be found",
    "code is provided",
    "software is provided",
    "code is accessible",
    "software is accessible",
    "code is archived",
    "software is archived",
    "code is deposited",
    "software is deposited",
    "code is shared",
    "software is shared",
    "code is released",
    "software is released",
    "code is published",
    "software is published",
    "code is submitted",
    "software is submitted",
    "code is uploaded",
    "software is uploaded",
    "code is included",
    "software is included",
    "code is stored",
    "software is stored",
    "code is hosted",
    "software is hosted",
    "code is found",
    "software is found",
    "code is obtained",
    "software is obtained",
    "code is retrieved",
    "software is retrieved",
    "code is requested",
    "software is requested",
    "code is supplied",
    "software is supplied",
    "code is given",
    "software is given",
    "code is sent",
    "software is sent",
    "code is delivered",
    "software is delivered",
    "code is distributed",
    "software is distributed",
    "code is transferred",
    "software is transferred",
    "code is transmitted",
    "software is transmitted",
    "code is communicated",
    "software is communicated",
    "code is disclosed",
    "software is disclosed",
    "code is referenced",
    "software is referenced",
    "code is cited",
    "software is cited",
    "code is listed",
    "software is listed",
    "code is documented",
    "software is documented",
    "code is reported",
    "software is reported",
    "code is noted",
    "software is noted",
    "code is mentioned",
    "software is mentioned",
    "code is identified",
    "software is identified",
    "code is named",
    "software is named",
    "code is labeled",
    "software is labeled",
    "code is tagged",
    "software is tagged",
    "code is marked",
    "software is marked",
    "code is highlighted",
    "software is highlighted",
    "code is emphasized",
    "software is emphasized",
    "code is described",
    "software is described",
    "code is explained",
    "software is explained",
    "code is clarified",
    "software is clarified",
    "code is interpreted",
    "software is interpreted",
    "code is detailed",
    "software is detailed",
    "code is specified",
    "software is specified",
    "code is itemized",
    "software is itemized",
    "code is enumerated",
    "software is enumerated",
    "code is catalogued",
    "software is catalogued",
    "code is registered",
    "software is registered",
    "code is recorded",
    "software is recorded",
    "supporting code",
    "supplementary code",
    "supplemental code",
    "supporting software",
    "supplementary software",
    "supplemental software",
    "github",
    "gitlab",
    "bitbucket",
    "source code",
    "scripts",
    "program",
    "algorithm",
]